version: '3.8'

services:
  # 1. الأبلكيشن بتاعك
  web-app:
    build: .
    container_name: hivebox-app
    ports:
      - "5001:5001"
    networks:
      - hivebox-network

  # 2. الجينكنز (متظبط على أحدث نسخة ومربوط بشغلك القديم)
  jenkins:
    image: jenkins/jenkins:latest # هنا خليناه يسحب أحدث نسخة متوفرة حالا
    container_name: hivebox-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - hivebox_project_jenkins_data:/var/jenkins_data # الفوليوم القديم بتاعك زي ما هو عشان جوبزك ترجع
      - /var/run/docker.sock:/var/run/docker.sock
      - k3s-config:/var/jenkins_home/.kube:ro
    networks:
      - hivebox-network

  # 3. كوبرنيتس (K3s) الخفيف
  k3s:
    image: rancher/k3s:v1.29.2-k3s1
    container_name: hivebox-k3s
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/config
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - k3s-config:/output
    ports:
      - "6443:6443"
    command: server --disable traefik --disable local-storage
    networks:
      - hivebox-network

volumes:
  hivebox_project_jenkins_data:
    external: true # عشان يلقط الفوليوم اللي شفناه في الصورة وميكريتش واحد جديد فاضي
  k3s-config:

networks:
  hivebox-network:
    driver: bridge